Jenkins-catalogue

diff --git a/8-Jenkins/8-01-catalogue/Jenkinsfile b/8-Jenkins/8-01-catalogue/Jenkinsfile
--- a/8-Jenkins/8-01-catalogue/Jenkinsfile
+++ b/8-Jenkins/8-01-catalogue/Jenkinsfile
@@ -49,63 +49,63 @@ pipeline {
                 }
             }
         }
-        stage('SonarQube Analysis') {
-            steps {
-                dir('8-Jenkins/8-01-catalogue') {
-                    // Name must match the SonarQube Server name in Manage Jenkins -> System
-                    withSonarQubeEnv('sonar-server') {
-                        sh """
-                            ${tool 'sonar-8'}/bin/sonar-scanner 
+        // stage('SonarQube Analysis') {
+        //     steps {
+        //         dir('8-Jenkins/8-01-catalogue') {
+        //             // Name must match the SonarQube Server name in Manage Jenkins -> System
+        //             withSonarQubeEnv('sonar-server') {
+        //                 sh """
+        //                     ${tool 'sonar-8'}/bin/sonar-scanner 
                         
-                        """
-                    }
-                }
-            }
-        }
-        stage('Quality Gate') {
-            steps {
-                timeout(time: 10, unit: 'MINUTES') {
-                    script {
-                        def qg = waitForQualityGate()
-                        if (qg.status != 'OK') {
-                            unstable(message: "Quality Gate failed with status: ${qg.status}")
-                        } 
-                    }     
-                }         
-            }            
-        }
-        stage('Check Dependabot Alerts') {
-            steps {
-                withCredentials([string(credentialsId: 'github-token', variable: 'GH_TOKEN')]) {
-                    sh '''
-                        set -e
+        //                 """
+        //             }
+        //         }
+        //     }
+        // }
+        // stage('Quality Gate') {
+        //     steps {
+        //         timeout(time: 10, unit: 'MINUTES') {
+        //             script {
+        //                 def qg = waitForQualityGate()
+        //                 if (qg.status != 'OK') {
+        //                     unstable(message: "Quality Gate failed with status: ${qg.status}")
+        //                 } 
+        //             }     
+        //         }         
+        //     }            
+        // }
+        // stage('Check Dependabot Alerts') {
+        //     steps {
+        //         withCredentials([string(credentialsId: 'github-token', variable: 'GH_TOKEN')]) {
+        //             sh '''
+        //                 set -e
 
-                        REPO="daws-90s/catalogue"
+        //                 REPO="https://github.com/pandalapadu/my-AWS-DevOps-Project//8-Jenkins/8-01-catalogue"
 
-                        curl -s -L \
-                        -H "Accept: application/vnd.github+json" \
-                        -H "Authorization: Bearer ${GH_TOKEN}" \
-                        -H "X-GitHub-Api-Version: 2026-03-10" \
-                        "https://api.github.com/repos/${REPO}/dependabot/alerts?state=open" \
-                        -o alerts.json
+        //                 curl -s -L \
+        //                 -H "Accept: application/vnd.github+json" \
+        //                 -H "Authorization: Bearer ${GH_TOKEN}" \
+        //                 -H "X-GitHub-Api-Version: 2026-03-10" \
+        //                 "https://api.github.com/repos/${REPO}/dependabot/alerts?state=open" \
+        //                 -o alerts.json
 
-                        echo "---- Open Dependabot Alerts ----"
-                        jq -r '.[] | "\\(.number)\\t\\(.security_vulnerability.severity)\\t\\(.dependency.package.name)\\t\\(.security_advisory.ghsa_id)"' alerts.json
+        //                 echo "---- Open Dependabot Alerts ----"
+        //                 jq -r '.[] | "\\(.number)\\t\\(.security_vulnerability.severity)\\t\\(.dependency.package.name)\\t\\(.security_advisory.ghsa_id)"' alerts.json
 
-                        HIGH_CRITICAL_COUNT=$(jq '[.[] | select(.security_vulnerability.severity == "high" or .security_vulnerability.severity == "critical")] | length' alerts.json)
+        //                 HIGH_CRITICAL_COUNT=$(jq '[.[] | select(.security_vulnerability.severity == "high" or .security_vulnerability.severity == "critical")] | length' alerts.json)
 
-                        echo "High/Critical alert count: ${HIGH_CRITICAL_COUNT}"
+        //                 echo "High/Critical alert count: ${HIGH_CRITICAL_COUNT}"
 
-                        if [ "$HIGH_CRITICAL_COUNT" -gt 0 ]; then
-                            echo "❌ Found ${HIGH_CRITICAL_COUNT} High/Critical severity dependency alert(s). Failing build."
-                            exit 1
-                        else
-                            echo "✅ No High/Critical dependency alerts found."
-                        fi
-                    '''
-                }
-            }
-        }
+        //                 if [ "$HIGH_CRITICAL_COUNT" -gt 0 ]; then
+        //                     echo "❌ Found ${HIGH_CRITICAL_COUNT} High/Critical severity dependency alert(s). Failing build."
+        //                     exit 1
+        //                 else
+        //                     echo "✅ No High/Critical dependency alerts found."
+        //                 fi
+        //             '''
+        //         }
+        //     }
+        // }
 
         stage('Docker Build') {
             steps {
